### PR TITLE
Added mangoszero

### LINKED ISSUE #11: Add MangosZero
Add Docker images, docker-compose file and Kubernetes descriptor file for MangosZero.

### PR DESCRIPTION
**Pull request by Wizofgoz**
Still needs to be tested but thought I'd open the PR to get it rolling. Please let me know if you spot any obvious errors. Cheers!

closes #11

### CODE REVIEW

**Comment by StephenSorriaux** [comment]
Hi, thanks for this PR. I will do some tests and let you know.

**Comment by StephenSorriaux** [comment]
Looks great, you did well with the `mangos0` and `character0` databases (and secrets and so on). I just added a commit since it would not build without it (cmake 3.8+ is now required)

Thanks again!

**Comment by StephenSorriaux** [comment]
The Docker image should be available during the night!

**Comment by Wizofgoz** [comment]
Awesome, glad I could help!

**Pull request merged**
